### ISSUE TITLE
improve directory listing icons etc

### ISSUE THREAD

**Issue by kzahel** [kzahel/web-server-chrome#13]

**Comment by kylecordes** [comment]
Here is a specific improvement that would help considerably. Make the directory listing sort the entries, like almost all other web servers do for listing pages.

**Comment by kzahel** [comment]
I agree. But sorted by filename? Do directories come first?
I was thinking of allowing sorting, too...
Didn't decide how featureful to make this yet

**Comment by kylecordes** [comment]
The bare minimum good answer is to just sort all of the entries. A slightly better answer is to sort first all the directories, then all the files. Doing that you would be on par with most other Web servers. I don't think it is necessary, or even all that helpful, to implement any more elaborate sorting, or any adjustments to sort order, etc. Basically the important thing is to get beyond what it has now, which is that they are an arbitrary/random order so that to use the list you have to manually hunt around for what you want.

**Comment by kzahel** [comment]
https://github.com/kzahel/web-server-chrome/commit/ef78dacc4caca1b4173caf92aedd031d5f858ce4
good suggestion. I did it this way and put an update to the store

**Comment by kzahel** [comment]
I just released an update with a prettier directory listing

**Comment by kzahel** [comment]
This has a disadvantage that something like Kodi or things that search directories for files to stream on media players cannot read this more dynamic JS generated directory listing. I may add an option to have a non-fancy directory listing. however, there are already so many options ...

**Comment by kzahel** [comment]
https://github.com/kzahel/web-server-chrome/commit/e3b8c844497e7a1ac92e3abf405ca3c1966c2790
If you append ?static=1 to the URL you'll get a static directory listing that does not require javascript

**Comment by kzahel** [comment]
it's also now an option you can set inside the app
