### ISSUE TITLE
Google is discontinuing apps for google chrome

### ISSUE THREAD

**Issue by ethanaobrien** [kzahel/web-server-chrome#259]
Google Chrome is discontinuing apps for google chrome for all platforms. What should we do. Would it be easy to migrate this to an extension?

[https://blog.chromium.org/2020/01/moving-forward-from-chrome-apps.html](https://blog.chromium.org/2020/01/moving-forward-from-chrome-apps.html)

**Comment by kzahel** [comment]
No it's not possible to make it an extension. Extensions can't have listening sockets

**Comment by ethanaobrien** [comment]
oop. I guess when chrome apps disappear we can just download an old version of google chrome so can continue to use this!

**Comment by kzahel** [comment]
That would be one option. Or you could install python and just run "python -m http.server" in the folder you want to serve.

**Comment by ethanaobrien** [comment]
@kzahel 
![Screenshot 2021-04-13 at 9 10 32 AM](https://user-images.githubusercontent.com/77750390/114566722-2a7f0080-9c38-11eb-9315-7405b283a49d.png)

Would this happen to work? It looks like it would allow an extension to listen

**Comment by ecc521** [comment]
You'll need a slightly more complex HTTP server than the simple python -m due to CORS in some cases.
I use a slightly modified version of https://gist.github.com/enjalot/2904124 now, since I've been having some issues with Web Server for Chrome erroring and not restarting properly (especially after the process owning the port is killed, etc) ​

It's been an **_extremely_** useful extension (especially on ChromeOS, where I'm still not sure there's a stable alternative), but between mediocre performance (a few MB/s, instead of >1 GB/s) and it not properly reconnecting (might be a Chrome bug, not the extension), etc, I've pretty much stopped using it

**Comment by ethanaobrien** [comment]
@ecc521   I've been looking at the code and I think I found the problem
Could you test this zip archive for me and tell me if it is fixed? Load the extension using the `load unpacked` option in `chrome://extensions`
https://drive.google.com/file/d/12Ewzalvx5ZMdleWcGnms4XFnHWC4j65_/view?usp=sharing

I created a pull request here:
https://github.com/kzahel/web-server-chrome/pull/264

**Comment by ethanaobrien** [comment]
closing in favor of #221
