### ISSUE TITLE
advanced settings options

### ISSUE THREAD

**Issue by kzahel** [kzahel/web-server-chrome#51]
we want to show additional settings that are not as common (e.g. CORS)

**Comment by ljgww** [comment]
CORS standard will likely be outdated with wider adoption of CSP
i do not see need for CORS for this kind of server, this is not meant to work as production server IMHO.

**Comment by kzahel** [comment]
I think some people use it for local development and want to do XHRs cross site. I am not certain why people keep requesting it in the app reviews TBH. CSP allows cross site XHR?

**Comment by ljgww** [comment]
I've read comments, & I can see some remote use for testing apps on another server (or providing specially crafted data). It would be great if requesters can explain use cases....

CORS and CSP are 'browser'/client thing supported by server - yes.

perhaps it would be better to have 'custom headers' OR some simple server side scripting/cgi (as I have asked in question on chrome store). Then one can craft special responses and custom headers.

**Comment by kzahel** [comment]
I agree it would be cool to have a little tab in the app where you can script / intercept request/response. a hook to set headers, at the very least. Or maybe even a GUI to do that.

There are a lot of examples of apps that do things like that in the web store, things that let you test HTTP requests to various domains. very slick UI

**Comment by kzahel** [comment]
regarding FQDN, it might be nice to make it easy to integrate a dynamic dns provider.

I'm also going to be adding in UPNP support soon, as I did in jstorrent, so you will have the option to have a public internet address. of course that may not work everywhere. but then there's also services like "localtunnel" that may have an API we could use

**Comment by ljgww** [comment]
I must admit that I do not know much about inner possibilities of chrome extensions, and I guess this the main reason as to why jstorrent looks like split into two parts. But your small web server holds great potential and if things are done in concise way that covers several use cases it could be fine tool for many applications. I would not however pursuit internet visibility as primary goal (although having casual server on dynamic dns would create fine use and surely gain users) , however I would be weary of lack of control when it comes to serving public internet user (perhaps someone will try to hack potential vulnerabilities and try to use it as back door or easy to install trojan).
Otherwise I concur with your line of thought. 
More zen (simple, conceptual) server is, imho, it serves user better (pushes user to be creative in use).

**Comment by kzahel** [comment]
added the CORS option and an "advanced settings" part, give it a try!

**Comment by AndrewKGuan** [comment]
can we have a way to edit CORS settings? More generally, can we edit what goes into the response headers.

**Comment by kzahel** [comment]
With any type of request? Like some option to always set a custom header? can you be more specific what you want?

**Comment by AndrewKGuan** [comment]
thanks for your prompt response, so I'm trying to test Accelerated Mobile Pages using 200OK and two obstacles I ran into:
- HTTPS (which I saw you mentioned it's work in progress on another thread) 
- CORS headers, documented here:
https://github.com/ampproject/amphtml/blob/master/spec/amp-cors-requests.md

It'd be great if the plug-in has somewhere to add/manage these headers.

Thank you!

**Comment by ethanaobrien** [comment]
@kzahel should this be closed?
