### ISSUE TITLE
Is https possible?

### ISSUE THREAD

**Issue by kylepaulsen** [kzahel/web-server-chrome#8]
I think I might already know the answer to this but wanted to know if you had any ideas on how we could get ssl working. I'm not sure if chrome supports it.

**Comment by simonh1000** [comment]
+1 I want to play around with PWA features - push notifications today - but all these advanced features need https. They work with localhost and http, but when it comes to checking on my Android phone I need to use a 192.168.0.xxx:1234 address and can't reach that on https

**Comment by blaibu** [comment]
@simonh1000 , this is an aside from web-server-chrome but to do what you want with Android, try using  https://www.charlesproxy.com/. you can intercept requests and inject charles' self signed cert as a workaround.

**Comment by hiNigel** [comment]
It would be really great if HTTPS was available. All browsers now disable access to location or webcam if there is no HTTPS. I know that for localhost address, there is an exception but sometimes I have to access to site on a simulator running in the system and browser on that simulator blocks the internal IP address because it is not HTTPS.

I think this would a problem in future for many as PWA's are getting popular and simulators are the easiest way to test the code.

I just run into this problem on iPhone simulator..

**Comment by kzahel** [comment]
Have you tried using ngrok ? https://ngrok.com/download

It won't work on ChromeOS but on all other platforms it will give you an HTTPS URL you can use. It requires you to be online, of course

**Comment by ethanaobrien** [comment]
@kzahel Does this need to be closed?
